export const MODAL_SUCCESS_IS_OPENED = 'MODAL_SUCCESS_IS_OPENED';
export const MODAL_SUCCESS_IS_CLOSED = 'MODAL_SUCCESS_IS_CLOSED';

export const MODAL_FAILED_IS_OPENED = 'MODAL_FAILED_IS_OPENED';
export const MODAL_FAILED_IS_CLOSED = 'MODAL_FAILED_IS_CLOSED';

export const START_TITLE_ANIMATION = 'START_TITLE_ANIMATION';